---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centosstream9
    image: quay.io/centos/centos:stream9
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
