changelog_filename_template: ../CHANGELOG.md
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
ignore_other_fragment_extensions: true
keep_fragments: false
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
output_formats:
  - md
prelude_section_name: release_summary
prelude_section_title: Release Summary
sanitize_changelog: true
sections:
  - - breaking_changes
    - Breaking Changes / Porting Guide
  - - major_changes
    - Major Changes
  - - minor_changes
    - Minor Changes
  - - deprecated_features
    - Deprecated Features
  - - removed_features
    - Removed Features (previously deprecated)
  - - security_fixes
    - Security Fixes
  - - bugfixes
    - Bugfixes
  - - known_issues
    - Known Issues
title: evgeni.router
trivial_section_name: trivial
use_fqcn: true
