---
kea_dhcp4_config:
  Dhcp4:
    interfaces-config:
      interfaces: "{{ kea_dhcp4_interfaces }}"
    subnet4: "{{ kea_dhcp4_subnets }}"
    loggers:
      - name: kea-dhcp4
        output_options:
          - output: /var/log/kea-dhcp4.log
        severity: "INFO"
        debuglevel: 0
